
[build]
functions = "netlify/functions"
publish = "dist"
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "20" # Explicitly setting Node.js version for consistency
NODE_ENV = "development" # Default to development for build context

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[dev]
functions = "netlify/functions"
publish = "dist"

[context]
[context.production]
[context.production.environment]
NODE_ENV = "production"

[context.deploy-preview]
[context.deploy-preview.environment]
NODE_ENV = "development"

[context.branch-deploy]
[context.branch-deploy.environment]
NODE_ENV = "development"
